### ISSUE TITLE
No such file or directory: './data/grouped_train.pkl'

### ISSUE THREAD

**Issue by lfoppiano** [billy-inn/HRERE#2]
I'm trying to reproduce your results and I've downloaded and installed your tools, and by following your tutorial I managed to reach this point: 

```
(tensorflow) a017873@yomite:~/development/relationship_extraction/HRERE$ python task.py --model best_real_hrere  --eval 10  --runs 10
Loading data...                                                                                                                                                                                   
  0%|                                                                                                                                                        | 0/10 [00:00<?, ?it/s, best loss: ?]
Traceback (most recent call last):
  File "task.py", line 326, in <module>
    main(options)
  File "task.py", line 320, in main
    optimizer.run()
  File "task.py", line 291, in run
    tpe.suggest, self.max_evals, trials)
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 388, in fmin
    show_progressbar=show_progressbar,
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/base.py", line 639, in fmin
    show_progressbar=show_progressbar)
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 407, in fmin
    rval.exhaust()
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 262, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 227, in run
    self.serial_evaluate()
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 141, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/base.py", line 844, in evaluate
    rval = self.fn(pyll_rval)
  File "task.py", line 275, in _obj
    self.task = Task(self.model_name, self.runs, param_dict, self.logger)
  File "task.py", line 24, in __init__
    words, positions, heads, tails, labels = pkl_utils._load(config.GROUPED_TRAIN_DATA)
  File "/home/a017873/development/relationship_extraction/HRERE/utils/pkl_utils.py", line 8, in _load
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/grouped_train.pkl'
```

I looked everywhere and could not find this file. Am I missing something? 

Thank you in advance

**Comment by billy-inn** [comment]
Have you run `python preprocess.py -p -g`?

**Comment by lfoppiano** [comment]
@billy-inn I have done the whole process again and it looks fine. It was something wrong I did. 
Thank you!
