### ISSUE TITLE
No such file or directory: './data/entity.npy'

### ISSUE THREAD

**Issue by lfoppiano** [billy-inn/HRERE#3]
I'm sorry, again me. I've tried again the whole process from scratch, and I've reached until the same point as #2 but now I have a new error: 

```
(tensorflow) a017873@yomite:~/development/relationship_extraction/HRERE$ python task.py --model best_real_hrere  --eval 10  --runs 10
Loading data...                                                                                                                                                                                   
  0%|                                                                                                                                                        | 0/10 [00:00<?, ?it/s, best loss: ?]/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL

101397 unique tokens have been found!                                                                                                                                                             
Preprocessing data...                                                                                                                                                                             
  0%|                                                                                                                                                        | 0/10 [07:40<?, ?it/s, best loss: ?]
Traceback (most recent call last):
  File "task.py", line 326, in <module>
    main(options)
  File "task.py", line 320, in main
    optimizer.run()
  File "task.py", line 291, in run
    tpe.suggest, self.max_evals, trials)
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 388, in fmin
    show_progressbar=show_progressbar,
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/base.py", line 639, in fmin
    show_progressbar=show_progressbar)
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 407, in fmin
    rval.exhaust()
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 262, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 227, in run
    self.serial_evaluate()
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/fmin.py", line 141, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/hyperopt/base.py", line 844, in evaluate
    rval = self.fn(pyll_rval)
  File "task.py", line 275, in _obj
    self.task = Task(self.model_name, self.runs, param_dict, self.logger)
  File "task.py", line 61, in __init__
    self.entity_embedding = np.load(config.ENTITY_EMBEDDING)
  File "/home/a017873/.conda/envs/tensorflow/lib/python3.7/site-packages/numpy/lib/npyio.py", line 422, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: './data/entity.npy'
(tensorflow) a017873@yomite:~/development/relationship_extraction/HRERE$ cd data/
```

Here the files inside `data`: 
```
(tensorflow) a017873@yomite:~/development/relationship_extraction/HRERE/data$ ls
entity1.npy    entity2.npy          grouped_test.pkl   prepare_data.py  relation2id.txt  test.tsv  train.tsv  triples.csv
entity2id.txt  glove.840B.300d.txt  grouped_train.pkl  relation1.npy    relation2.npy    test.txt  train.txt
```

Thank you in advance
Luca

**Comment by billy-inn** [comment]
For argument, you should use `--model best_complex_hrere` instead of `--model best_real_here`. "real" here indicates embeddings  in real space like TransE and DistMult.

**Comment by lfoppiano** [comment]
Thanks.
